//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWPZU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_new
    {
        public int Id { get; set; }
        public Nullable<int> AirlineId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> AirportId { get; set; }
        public Nullable<int> FlightStatusId { get; set; }
        public Nullable<int> FlightTypeId { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual AirPort AirPort { get; set; }
        public virtual FlightStatu FlightStatu { get; set; }
        public virtual FlightType FlightType { get; set; }
    }
}
