//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWPZU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotal
    {
        public int Id { get; set; }
        public string NameAr { get; set; }
        public string NameEng { get; set; }
        public string Img { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public Nullable<int> Star { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
